config/routes.rb
Rails.application.routes.draw do
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  get '/logout',  to: 'sessions#destroy'
  get 'pages/about'
  get 'pages/homepage'
  #root "pages#homepage"
  root "powers#index"
  resources :powers
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/power.rb
class Power < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
  private
   # ログイン済みユーザーかどうか確認
    def logged_in_user
      unless logged_in?
        redirect_to login_url
      end
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end
end

app/controllers/powers_controller.rb
class PowersController < ApplicationController
  before_action :set_power, only: %i[ show edit update destroy ]
  before_action :logged_in_user

  # GET /powers or /powers.json
  def index
    @powers = Power.all
  end

  # GET /powers/1 or /powers/1.json
  def show
  end

  # GET /powers/new
  def new
    @power = Power.new
  end

  # GET /powers/1/edit
  def edit
  end

  # POST /powers or /powers.json
  def create
    @power = Power.new(power_params)

    respond_to do |format|
      if @power.save
        format.html { redirect_to power_url(@power), notice: "Power was successfully created." }
        format.json { render :show, status: :created, location: @power }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @power.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /powers/1 or /powers/1.json
  def update
    respond_to do |format|
      if @power.update(power_params)
        format.html { redirect_to power_url(@power), notice: "Power was successfully updated." }
        format.json { render :show, status: :ok, location: @power }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @power.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /powers/1 or /powers/1.json
  def destroy
    @power.destroy

    respond_to do |format|
      format.html { redirect_to powers_url, notice: "Power was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_power
      @power = Power.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def power_params
      params.require(:power).permit(:e1, :e2, :e3, :e4, :e5, :e6, :e7, :e8, :p1, :p2, :p3, :p4, :p5, :p6, :p7, :p8)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new

  end
  
  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      #redirect_to root_url
      redirect_to new_power_url
    else
      render 'new'
    end
  end

  def destroy
    log_out if logged_in?
    redirect_to root_url
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/powers_helper.rb
module PowersHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  # 渡されたユーザーでログインする
  def log_in(user)
    session[:user_id] = user.id
  end

  # 現在ログイン中のユーザーを返す (いる場合)
  def current_user
    if session[:user_id]
      #@current_user = @current_user || User.find_by(id: session[:user_id])と同じ意味
      @current_user ||= User.find_by(id: session[:user_id])
    end
  end

  #受け取ったユーザーがログイン中のユーザーと一致すればtrueを返す
  def current_user?(user)
    user == current_user
  end

  # ユーザーがログインしていればtrue、その他ならfalseを返す
  def logged_in?
    !current_user.nil?
  end

  # 現在のユーザーをログアウトする
  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
  
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NohohonSample002</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <%= javascript_importmap_tags %>
  </head>

  <body>

  <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">The power app</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link <%= 'active' if current_page?(controller: 'pages', action: 'homepage') %>" href="/">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link <%= 'active' if current_page?(controller: 'powers') %>" href="/powers">Powers</a>
        </li>
        <li class="nav-item">
          <a class="nav-link <%= 'active' if current_page?(controller: 'pages', action: 'about') %>" href="/pages/about">About</a>
        </li>
      </ul>
    </div>
  </div>
</nav>

    <div class="container">
      <%= yield %>
    </div>
  </body>

<footer class="mt-5 text-center">
  <div class="container">
    NOHOHON<%= Time.now.year %>
  </div>
</footer>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>

</html>

app/views/pages/about.html.erb
<h1>About me</h1>
<p>Hello there! I am NOHOHON HERE and this is my amazing app!</p>

app/views/pages/homepage.html.erb
<div class="px-4 py-5 my-5 text-center">
  <h1 class="display-5 fw-bold">The powers app</h1>
  <div class="col-lg-6 mx-auto">
    <p class="lead mb-4">Welcome to my powers app!</p>
  </div>
</div>

app/views/powers/_form.html.erb
<%= form_with(model: power) do |form| %>
  <% if power.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(power.errors.count, "error") %> prohibited this power from being saved:</h2>

      <ul>
        <% power.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

<table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">電力量</th>
      <th scope="col">単価</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th scope="row">1</th>
      <td><%= form.number_field :e1 %></td>
      <td><%= form.number_field :p1 %></td>
    </tr>
    <tr>
      <th scope="row">2</th>
      <td><%= form.number_field :e2 %></td>
      <td><%= form.number_field :p2 %></td>
    </tr>
    <tr>
      <th scope="row">3</th>
      <td><%= form.number_field :e3 %></td>
      <td><%= form.number_field :p3 %></td>
    </tr>
    <tr>
      <th scope="row">４</th>
      <td><%= form.number_field :e4 %></td>
      <td><%= form.number_field :p4 %></td>
    </tr>
   <tr>
      <th scope="row">5</th>
      <td><%= form.number_field :e5 %></td>
      <td><%= form.number_field :p5 %></td>
    </tr>
   <tr>
      <th scope="row">6</th>
      <td><%= form.number_field :e6 %></td>
      <td><%= form.number_field :p6 %></td>
    </tr>
   <tr>
      <th scope="row">7</th>
      <td><%= form.number_field :e7 %></td>
      <td><%= form.number_field :p7 %></td>
    </tr>
   <tr>
      <th scope="row">8</th>
      <td><%= form.number_field :e8 %></td>
      <td><%= form.number_field :p8 %></td>
    </tr>
   </tbody>
</table>



  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/powers/_logged_in.html.erb
<h1>Powers</h1>

<div id="powers">
  <% @powers.each do |power| %>
    <%= render power %>
    <p>
      <%= link_to "Show this power", power %>
    </p>
  <% end %>
</div>

<%= link_to "New power", new_power_path %>
<%= link_to "Logout", logout_path, method: :delete %>

app/views/powers/_not_logged_in.html.erb
<p>Please login!!</p>
<%= link_to "Login", login_path%>

app/views/powers/_power.html.erb
<div id="<%= dom_id power %>">
  <p>
    <strong>E1:</strong>
    <%= power.e1 %>
  </p>

  <p>
    <strong>E2:</strong>
    <%= power.e2 %>
  </p>

  <p>
    <strong>E3:</strong>
    <%= power.e3 %>
  </p>

  <p>
    <strong>E4:</strong>
    <%= power.e4 %>
  </p>

  <p>
    <strong>E5:</strong>
    <%= power.e5 %>
  </p>

  <p>
    <strong>E6:</strong>
    <%= power.e6 %>
  </p>

  <p>
    <strong>E7:</strong>
    <%= power.e7 %>
  </p>

  <p>
    <strong>E8:</strong>
    <%= power.e8 %>
  </p>

  <p>
    <strong>P1:</strong>
    <%= power.p1 %>
  </p>

  <p>
    <strong>P2:</strong>
    <%= power.p2 %>
  </p>

  <p>
    <strong>P3:</strong>
    <%= power.p3 %>
  </p>

  <p>
    <strong>P4:</strong>
    <%= power.p4 %>
  </p>

  <p>
    <strong>P5:</strong>
    <%= power.p5 %>
  </p>

  <p>
    <strong>P6:</strong>
    <%= power.p6 %>
  </p>

  <p>
    <strong>P7:</strong>
    <%= power.p7 %>
  </p>

  <p>
    <strong>P8:</strong>
    <%= power.p8 %>
  </p>

</div>

app/views/powers/edit.html.erb
<h1>Editing power</h1>

<%= render "form", power: @power %>

<br>

<div>
  <%= link_to "Show this power", @power %> |
  <%= link_to "Back to powers", powers_path %>
</div>

app/views/powers/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Power app</h1>
<% if logged_in? %>
  <%= render 'powers/logged_in' %>
<% else %>
  <%= render 'powers/not_logged_in' %>
<% end %>

app/views/powers/new.html.erb
<h1>New power</h1>

<%= render "form", power: @power %>

<br>

<div>
  <%= link_to "Back to powers", powers_path %>
</div>

app/views/powers/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @power %>

<div>
  <%= link_to "Edit this power", edit_power_path(@power) %> |
  <%= link_to "Back to powers", powers_path %>

  <%= button_to "Destroy this power", @power, method: :delete %>
</div>